"""Added confirmed_email boolean

Revision ID: 13ee3b7b6105
Revises: 8fd1863b32cd
Create Date: 2024-07-26 11:04:07.133675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13ee3b7b6105'
down_revision = '8fd1863b32cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed_email', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('confirmed_email')

    # ### end Alembic commands ###
