"""Added energy coverage settings

Revision ID: 39965bbf5aac
Revises: 75b0d1d4d471
Create Date: 2024-07-23 09:57:00.417558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39965bbf5aac'
down_revision = '75b0d1d4d471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('inclusion', sa.Boolean(), nullable=False),
    sa.Column('heat_norm', sa.Float(), nullable=False),
    sa.Column('weather_norm_heat', sa.Float(), nullable=False),
    sa.Column('weather_norm_cold', sa.Float(), nullable=False),
    sa.Column('dist_heating_norm', sa.Float(), nullable=False),
    sa.Column('dist_cooling_norm', sa.Float(), nullable=False),
    sa.Column('reporting_coverage', sa.Float(), nullable=False),
    sa.Column('off_site_settings', sa.Float(), nullable=False),
    sa.Column('occupancy_norm', sa.Float(), nullable=False),
    sa.Column('grid_elec_coverage', sa.Float(), nullable=False),
    sa.Column('natural_gas_coverage', sa.Float(), nullable=False),
    sa.Column('fuel_oil_coverage', sa.Float(), nullable=False),
    sa.Column('dist_heating_coverage', sa.Float(), nullable=False),
    sa.Column('dist_cooling_coverage', sa.Float(), nullable=False),
    sa.Column('o1_coverage', sa.Float(), nullable=False),
    sa.Column('o2_coverage', sa.Float(), nullable=False),
    sa.Column('building_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_settings_id'), ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_id'))
        batch_op.drop_index(batch_op.f('ix_settings_building_id'))

    op.drop_table('settings')

    # ### end Alembic commands ###
