"""Added construction year

Revision ID: 67212e1ef1c3
Revises: b923bf100b1b
Create Date: 2024-07-25 12:34:45.730896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67212e1ef1c3'
down_revision = 'b923bf100b1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('construction_year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.drop_column('construction_year')

    # ### end Alembic commands ###
