"""Mandatory constuction year

Revision ID: 8fd1863b32cd
Revises: 67212e1ef1c3
Create Date: 2024-07-25 12:42:16.818862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd1863b32cd'
down_revision = '67212e1ef1c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.alter_column('construction_year',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.alter_column('construction_year',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
