"""Mandatory confirmed_email field

Revision ID: c91d18078b19
Revises: 13ee3b7b6105
Create Date: 2024-07-26 11:10:06.119499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c91d18078b19'
down_revision = '13ee3b7b6105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('confirmed_email',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('confirmed_email',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
