"""Added new validation for Select Fields

Revision ID: cd8d82beb809
Revises: fede56ed5866
Create Date: 2024-07-10 11:57:53.064070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd8d82beb809'
down_revision = 'fede56ed5866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.alter_column('property_type',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.Enum('RSF', 'RMF', name='propertytypes'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.alter_column('property_type',
               existing_type=sa.Enum('RSF', 'RMF', name='propertytypes'),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)

    # ### end Alembic commands ###
